import { InfoOutlined } from '@ant-design/icons';

export default [
  {
    path: '/auth',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/auth/login',
        component: './auth/login',
        isEmployee: false,
      },
      {
        name: 'login',
        path: '/auth/mobile/login',
        component: './auth/login',
        isEmployee: false,
      },
      {
        name: 'login',
        path: '/auth/employee/login',
        component: './auth/login',
        isEmployee: true,
      },
      {
        name: 'restore-password',
        path: '/auth/restore-password',
        component: './auth/restore-password',
      },
      {
        name: 'reset-password',
        path: '/auth/reset-password',
        component: './auth/reset-password',
      },
      {
        name: 'register',
        path: '/auth/register',
        component: './auth/register',
      },
      {
        name: 'register-confirm',
        path: '/auth/register/confirm/:username',
        component: './auth/register/confirm',
      },
      {
        name: 'page-android',
        path: '/auth/page-android',
        component: './auth/page-android',
      },
      {
        name: 'page-ios',
        path: '/auth/page-ios',
        component: './auth/page-ios',
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/',
    name: 'welcome',
    icon: 'smile',
    component: './home',
    hideInMenu: true,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'BarChartOutlined',
    component: './dashboard',
  },
  // {
  //   path: '/page-android',
  //   name: 'page-android',
  //   component: '/auth/page-android',
  //   hideInMenu: true,
  // },
  // {
  //   path: '/page-ios',
  //   name: 'page-ios',
  //   component: './page-ios',
  //   hideInMenu: true,
  // },
  {
    path: '/order',
    name: 'order',
    icon: 'SendOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/order/create',
        name: 'create',
        icon: 'crown',
        component: './order/create',
        access: 'canAccessMenu',
        layout: {
          hideFooter: true,
        },
      },
      {
        path: '/order/batch/create',
        name: 'create-batch',
        icon: 'crown',
        component: './order/create',
        access: 'canAccessMenu',
        layout: {
          hideFooter: true,
        },
      },
      {
        path: '/order/international/create',
        name: 'create-international',
        icon: 'crown',
        component: './order/international',
        access: 'canAccessMenu',
        layout: {
          hideFooter: true,
        },
      },
      {
        path: '/order/import',
        name: 'import',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './order/import',
      },
      {
        path: '/order/edit/:id',
        name: 'order-item',
        icon: 'crown',
        access: 'canAccessMenu',
        hideInMenu: true,
        component: './order/create',
      },
    ],
  },
  {
    path: '/manage',
    name: 'manager',
    icon: 'ZoomInOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/manage/order-manager',
        name: 'order-manager',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './manager/order-manager',
      },
      {
        path: '/manage/order-manager-employee',
        name: 'order-manager-employee',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './manager/order-manager-employee',
      },
      {
        path: '/manage/correction-manager',
        name: 'correction-manager',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './manager/correction-manager',
      },
      {
        path: '/manage/correction-manager/correct/:case_type_id/:id',
        name: 'correction',
        icon: 'crown',
        component: './order/create',
        hideInMenu: true,
        access: 'canAccessMenu',
        layout: {
          hideFooter: true,
        },
      },
      {
        path: '/manage/ticket',
        name: 'ticket',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './manager/ticket',
        routes: [
          {
            path: '/manage/ticket',
            name: 'ticket-viewer',
            icon: 'PlusCircleOutlined',
            hideInMenu: true,
            access: 'canAccessMenu',
            component: './manager/ticket/ticket-viewer',
            // hideInSubMenu: true,
          },
          {
            path: '/manage/ticket/search-ticket',
            name: 'search-ticket',
            icon: 'SendOutlined',
            hideInMenu: true,
            access: 'canAccessMenu',
            component: './manager/ticket/search-ticket',
            // hideInSubMenu: true,
          },
        ],
      },
      {
        path: '/manage/library-manager',
        name: 'library-manager',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './manager/library-manager',
      },
      {
        path: '/manage/library-manager/viewitem',
        //name: 'library-manager',
        icon: 'crown',
        hideInMenu: true,
        // access: 'canAccessMenu',
        component: './manager/library-manager/viewitem',
      },
      {
        path: '/manage/order-manager/sender/:id',
        // name: 'order-detail',
        icon: 'crown',
        // access: 'canAccessMenu',
        component: './setting/orderhdr-item/orderHdrViewer',
      },
      {
        path: '/manage/order-manager/receiver/:id',
        // name: 'order-detail',
        icon: 'crown',
        // access: 'canAccessMenu',
        component: './setting/orderhdr-item/orderReceived',
      },
      {
        path: '/manage/notify-manager',
        name: 'notify-manager',
        icon: 'crown',
        hideInMenu: true,
        // access: 'canAccessMenu',
        component: './manager/notify-manager',
      },
    ],
  },
  {
    path: '/for-control',
    name: 'for-control',
    icon: 'RetweetOutlined',
    access: 'canAccessMenu',
    // redirect: '/for-control/import',
    // component: './setting/for-control',
    routes: [
      {
        path: '/for-control/control',
        name: 'control',
        icon: 'crown',
        access: 'canAccessMenu',
        // hideInMenu: true,
        component: './for-control/control',
      },
      {
        path: '/for-control/import',
        name: 'import',
        code: 'for-control-import',
        icon: 'crown',
        access: 'canAccessMenu',
        // hideInMenu: true,
        component: './for-control/import',
      },
      {
        path: '/for-control/search',
        name: 'search',
        icon: 'crown',
        access: 'canAccessMenu',
        // hideInMenu: true,
        component: './for-control/search',
      },
      {
        path: '/for-control/detail-control/:id',
        name: 'detail-control',
        icon: 'crown',
        hideInMenu: true,
        component: './for-control/detail-control',
        // hideInSubMenu: true,
      },
      {
        path: '/for-control/report-control',
        name: 'report-control',
        icon: 'crown',
        access: 'canAccessMenu',
        // hideInMenu: true,
        component: './for-control/report-control',
      },
    ],
  },
  {
    path: '/utilities',
    name: 'utilities',
    icon: 'ProfileOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/utilities/nearby-post',
        name: 'nearby-post',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './utilities/nearby-post',
      },
      {
        path: '/utilities/fee-lookup',
        name: 'fee-lookup',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './utilities/fee-lookup',
      },
      {
        path: '/utilities/hs-code',
        name: 'hs-code',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './utilities/hs-code',
      },
      {
        path: '/utilities/region-limit',
        name: 'region-limit',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './utilities/region-limit',
      },
    ],
  },
  {
    path: '/questions',
    name: 'questions',
    icon: 'QuestionCircleOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/questions/news/3',
        name: 'library-questions',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './questions/news',
      },
      {
        path: '/questions/news/4',
        name: 'library-instruction',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './questions/news',
      },
      {
        path: '/questions/news/2',
        name: 'library-regulationsAndPolicies',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './questions/news',
      },
    ],
  },
  {
    path: '/news',
    name: 'news',
    icon: 'ReadOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/news/news-general/1',
        name: 'library-news',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './news/news-general',
      },
      {
        path: '/news/news-general/5',
        name: 'library-preferential',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './news/news-general',
      },
      // {
      //   path: '/news/news-general/2',
      //   name: 'library-regulationsAndPolicies',
      //   icon: 'crown',
      //   component: './news/news-general',
      // },
    ],
  },

  {
    path: '/route-service',
    name: 'route-service',
    icon: 'NodeExpandOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/route-service/parity',
        name: 'parity',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './route-service',
      },
    ],
  },
  {
    path: '/postal-collection',
    name: 'postal-collection',
    icon: 'DropboxOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/postal-collection/collection-news',
        name: 'collection-news',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './postal-collection/collection-news',
      },
      // {
      //   path: '/postal-collection/create',
      //   name: 'create-collection-news',
      //   icon: 'crown',
      //   access: 'canAccessMenu',
      //   component: './postal-collection/collection-news/create',
      // },
      {
        path: '/postal-collection/collection-schedule',
        name: 'collection-schedule',
        icon: 'crown',
        access: 'canAccessMenu',
        component: './postal-collection/collection-schedule',
      },
      // {
      //   path: '/postal-collection/create-schedule',
      //   name: 'create-collection-schedule',
      //   icon: 'crown',
      //   access: 'canAccessMenu',
      //   component: './postal-collection/collection-schedule/create',
      // },
    ],
  },

  // {
  //   path: '/customer',
  //   name: 'customer',
  //   icon: 'TeamOutlined',
  //   routes: [
  //     {
  //       path: '/customer/search',
  //       name: 'search',
  //       icon: 'crown',
  //       component: './customer/search-customer',
  //     },
  //     {
  //       path: '/customer/create',
  //       name: 'create',
  //       icon: 'crown',
  //       component: './customer/create-customer',
  //     },
  //   ],
  // },
  {
    path: '/setting',
    name: 'setting',
    icon: 'SettingOutlined',
    access: 'canAccessMenu',
    // component: './setting',
    // redirect: '/setting/employee-manager',
    routes: [
      {
        path: '/setting/account',
        name: 'account',
        icon: 'crown',
        component: './setting/account',
        access: 'canAccessMenu',
        routes: [
          // {
          //   path: '/setting/account',
          //   name: 'employee-manager',
          //   icon: 'TeamOutlined',
          //   hideInMenu: true,
          //   redirect: '/setting/account/employee-manager',
          //   hideInSubMenu: true,
          // },
          {
            path: '/setting/account/employee-manager',
            name: 'employee-manager',
            icon: 'TeamOutlined',
            access: 'canAccessMenu',
            component: './setting/account/employee-manager',
            hideInMenu: true,
            exact: true,
          },
          {
            path: '/setting/account/account-information',
            name: 'account-information',
            icon: 'InfoCircleOutlined',
            access: 'canAccessMenu',
            component: './setting/account/account-information',
            hideInMenu: true,
          },
          {
            path: '/setting/account/change-password',
            name: 'change-password',
            icon: 'KeyOutlined',
            component: './setting/account/change-password',
            hideInMenu: true,
            access: 'canAccessMenu',
          },
          {
            path: '/setting/account/config-notification',
            name: 'config-notification',
            icon: 'BulbOutlined',
            component: './setting/account/config-notification',
            hideInMenu: true,
            access: 'canAccessMenu',
          },
          {
            path: '/setting/account/print-configuration',
            name: 'print-configuration',
            icon: 'PrinterOutlined',
            component: './setting/account/print-configuration',
            hideInMenu: true,
            access: 'canAccessMenu',
          },
          {
            path: '/setting/account/partner-configuration',
            name: 'partner-configuration',
            icon: 'UserSwitchOutlined',
            component: './setting/account/partner-configuration',
            hideInMenu: true,
            // hideInSubMenu: true,
            access: 'canAccessMenu',
          },
          {
            path: '/setting/account/config-webhook',
            name: 'config-webhook',
            icon: 'SettingOutlined',
            component: './setting/account/config-webhook',
            hideInMenu: true,
            // hideInSubMenu: true,
            access: 'canAccessMenu',
          },
        ],
      },
      // {
      //   path: '/setting/group/group-manager',
      //   name: 'group',
      //   icon: 'crown',
      //   component: './setting/group/group-manager',
      //    routes: [
      //   //   {
      //   //     path: '/setting/group/group-manager',
      //   //     name: 'group-manager',
      //   //     icon: 'crown',
      //   //     component: './setting/group/group-manager',
      //   //     hideInMenu: true,
      //   //   },
      //   // ],
      // },
      // {
      //   path: '/setting/assign-account',
      //   name: 'assign-account',
      //   icon: 'crown',
      //   component: './setting/assign-account',
      // },
      // {
      //   path: '/setting/assign-user',
      //   name: 'assign-user',
      //   icon: 'crown',
      //   component: './setting/assign-user',
      // },
      {
        path: '/setting/sender-manager',
        name: 'sender-manager',
        icon: 'crown',
        component: './setting/sender-manager',
        access: 'canAccessMenu',
      },
      {
        path: '/setting/sender-manager-create',
        name: 'sender-manager-create',
        icon: 'crown',
        component: './setting/sender-manager-create',
        access: 'canAccessMenu',
        // hideInMenu: true,
      },
      {
        path: '/setting/sender-manager-national-create',
        name: 'sender-manager-national-create',
        icon: 'crown',
        component: './setting/sender-manager-national-create',
        access: 'canAccessMenu',
        // hideInMenu: true,
      },
      {
        path: '/setting/route-service-same-price',
        name: 'route-service-same-price',
        icon: 'crown',
        component: './route-service',
        access: 'canAccessMenu',
        // hideInMenu: true,
      },
      {
        path: '/setting/route-service-same-price/new-mixed-price',
        name: 'new-mixed-price',
        icon: 'crown',
        component: './route-service/NewMixedPrice',
        access: 'canAccessMenu',
        hideInMenu: true,
        exact: true,
      },
      {
        path: '/setting/route-service-same-price/edit-mixed-price/:id',
        name: 'edit-mixed-price',
        icon: 'crown',
        component: './route-service/NewMixedPrice',
        access: 'canAccessMenu',
        hideInMenu: true,
        exact: true,
      },
      {
        path: '/setting/route-service-same-price/new-fast-price',
        name: 'new-fast-price',
        icon: 'crown',
        component: './route-service/NewFastPrice',
        access: 'canAccessMenu',
        hideInMenu: true,
        exact: true,
      },
      {
        path: '/setting/receiver-manager',
        name: 'receiver-manager',
        icon: 'crown',
        component: './setting/receiver-manager',
        access: 'canAccessMenu',
      },
      {
        path: '/setting/product',
        name: 'product',
        icon: 'crown',
        component: './setting/product/create-product',
        access: 'canAccessMenu',
      },
      {
        path: '/setting/product-national',
        name: 'product-national',
        icon: 'crown',
        component: './setting/product-national/create-product',
        access: 'canAccessMenu',
      },

      {
        path: '/setting/order-template',
        name: 'order-template',
        icon: 'crown',
        component: './setting/orderTemplate',
        access: 'canAccessMenu',
      },
      {
        path: '/setting/order-template/create',
        name: 'order-template-create',
        icon: 'crown',
        component: './setting/orderTemplate/create',
        hideInMenu: true,
        access: 'canAccessMenu',
      },
      {
        path: '/setting/order-template/:id',
        name: 'order-template-item',
        icon: 'crown',
        component: './setting/orderTemplate/create',
        hideInMenu: true,
        access: 'canAccessMenu',
      },
      // {
      //   path: '/setting/orderhdr-item',
      //   name: 'orderhdr-item',
      //   icon: 'crown',
      //   component: './setting/orderhdr-item',
      // },
    ],
  },
  {
    path: '/manager-user',
    name: 'manager-user',
    icon: 'SolutionOutlined',
    access: 'canAccessMenu',
    routes: [
      {
        path: '/manager-user/create-customer',
        name: 'create-customer',
        icon: 'crown',
        component: './manager-user/create-customer',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/search-customer',
        name: 'search-customer',
        icon: 'crown',
        component: './manager-user/search-customer',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/assign-account',
        name: 'assign-account',
        icon: 'crown',
        component: './manager-user/assign-account',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/group/group-manager',
        name: 'group',
        icon: 'crown',
        component: './manager-user/group/group-manager',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/assign-user',
        name: 'assign-user',
        icon: 'crown',
        component: './manager-user/assign-user',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/menu',
        name: 'menu',
        icon: 'crown',
        component: './category/menu',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/partner-category',
        name: 'partner-category',
        icon: 'crown',
        component: './category/partner-category',
        access: 'canAccessMenu',
        // hideInMenu: true,
      },
      {
        path: '/manager-user/declare-connect-bank',
        name: 'declare-connect-bank',
        icon: 'crown',
        component: './manager-user/declare-connect-bank',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/approval-connect-bank',
        name: 'approval-connect-bank',
        icon: 'crown',
        component: './manager-user/approval-connect-bank',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/account-replace',
        name: 'account-replace',
        icon: 'crown',
        component: './manager-user/account-replace',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/service-configuration',
        name: 'service-configuration',
        icon: 'crown',
        component: './manager-user/service-configuration',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/vas-configuration',
        name: 'vas-configuration',
        icon: 'crown',
        component: './manager-user/vas-configuration',
        access: 'canAccessMenu',
      },
      {
        path: '/manager-user/use-vas-configuration',
        name: 'use-vas-configuration',
        icon: 'crown',
        component: './manager-user/use-vas-configuration',
        access: 'canAccessMenu',
      },
    ],
  },
  {
    path: '/system',
    name: 'system',
    icon: 'SettingOutlined',
    hideInMenu: true,
    component: './system',
    routes: [
      {
        path: '/system/log',
        name: 'log',
        icon: 'crown',
        component: './system/applog',
      },
      {
        path: '/system/log-login',
        name: 'log-login',
        icon: 'crown',
        component: './system/applog-login',
      },
      {
        path: '/system/statistic-create-account',
        name: 'statistic-create-account',
        icon: 'crown',
        component: './system/statistic-create-account',
      },
    ],
  },

  {
    path: '/category',
    name: 'category',
    icon: 'ProfileOutlined',
    hideInMenu: true,
    routes: [
      {
        path: '/category/uom',
        name: 'uom',
        icon: 'crown',
        component: './category/uom',
      },
      {
        path: '/category/notify',
        name: 'notify',
        icon: 'crown',
        component: './category/notify',
      },
      {
        path: '/category/mauin',
        name: 'mauin',
        icon: 'crown',
        component: './category/mauin',
      },
      {
        path: '/category/appparam',
        name: 'appparam',
        icon: 'crown',
        component: './category/appparam',
      },
    ],
  },
  {
    component: './404',
  },
];
